### ISSUE TITLE
setup.py doesn't properly overwrite tovid-init

### ISSUE THREAD

**Issue by tovid-suite** [tovid-suite/tovid#120] opened 2015-03-16 13:33 UTC
_From [asch...@gmail.com](https://code.google.com/u/110263688088614489451/) on June 01, 2010 08:32:13_

As per Summary and by request of Grepper, dropping in a ticket to remind
you all that setup.py doesn't properly overwrite tovid-init.

_Original issue: http://code.google.com/p/tovid/issues/detail?id=120_

**Comment by grepper** [comment] 2015-03-16 13:33
_From [wapcaplet88](https://code.google.com/u/wapcaplet88/) on June 01, 2010 16:34:20_

This ought to be fixed in r3156 --tovid-init should get rebuilt no matter what. Still
needs further testing to confirm.

**Status:** Started  
  **Owner:** wapcaplet88  
  **Labels:** Type-Defect

**Comment by grepper** [comment] 2015-04-13 14:19
I believe this issue has been fixed. Please reopen if this is not the case, I have not seen any reports of this problem and cannot reproduce it. Closing.

**Closed by grepper** 2015-04-13 14:19 UTC
Labels: bug, imported
